### Lab Assignment: Python Warmup and Logfile Analytics

### University of Virginia
### DS 5110: Big Data Systems
### Last Updated: January 23, 2026

---

This lab consists of two parts:

- Part 1 is the Python warmup
- Part 2 is the logfile analytics in PySpark

Answer the questions in this assignment, showing all code and solutions.

**Total points: 20**

---

### Part 1: Python Warmup

1) (1 PT) Rename this notebook to JupyterTutorial_[your_initials], where you will enter your initials in place of [your_initials].

2) (1 PT) In the cell below, enter a list of data science topics you find interesting.  Use the markdown style (you will need to change the style from the Code style).

- Time Series Analysis
- Biostatistics
- Genomics
- Political Science

3) (1 PT) In the cell below, enter the following Python list:  

some_vals = [1, 6, 10, 44]  

You will use the Code style, run the cell, and print the list.

In [21]:
some_vals = [1,6,10,44]
some_vals

[1, 6, 10, 44]

4) (1 PT) Use a list comprehension to return a filtered list containing only the values greater than 6.  
Call this list *some_vals_filtered* and print it.

In [20]:
[val for val in some_vals if val > 6]

[10, 44]

Next, a small pandas dataframe is constructed.

In [54]:
import pandas as pd

df = pd.DataFrame({'first_name': ['Andy','Crystal'],
                   'domain_facebook' : [1,1],
                   'domain_foursquare' : [0,0],
                   'age' : [20, 32]})
df

  first_name  domain_facebook  domain_foursquare  age
0       Andy                1                  0   20
1    Crystal                1                  0   32

5) (1 PT) In the cell below, write a list comprehension that returns the fields names in the dataframe `df` containing the string *domain*.  Run the cell to verify the correct result.

In [19]:
[col for col in df.columns if 'domain' in col]

['domain_facebook', 'domain_foursquare']

6) (1 PT) Use the list comprehension from (5) to index into `df` and show the data for columns containing *domain*

In [24]:
domain_cols = [col for col in df.columns if 'domain' in col]

df[domain_cols]

   domain_facebook  domain_foursquare
0                1                  0
1                1                  0

7) (1 PT) In the cell below, print the *domain_facebook* column

In [27]:
df['domain_foursquare']

0    0
1    0
Name: domain_foursquare, dtype: int64

8) (1 PT) In the cell below, print the row with index 1.

In [33]:
df.loc[[1]]

  first_name  domain_facebook  domain_foursquare  age
1    Crystal                1                  0   32

9) (1 PT) Next, you will cube the *age* column of `df` and assign the result to a new column called *agecube*.

Specifically, call the `apply` method with a `lambda function` inside to cube the *age* column.  
Print the dataframe.

In [47]:
df = df.assign(agecube = lambda x: (x['age'] ** 3))
df

  first_name  domain_facebook  domain_foursquare  age  agecube
0       Andy                1                  0   20     8000
1    Crystal                1                  0   32    32768

10) (1 PT) Given the list of strings below, form one string, placing semicolons between each word.  It should look like this:  

`'the;quick;brown;fox'`

Print the resulting string.

In [49]:
some_list = ['the','quick','brown','fox']

In [51]:
some_str = ";".join(some_list)
some_str

'the;quick;brown;fox'

---

### Part 2: Logfile Analytics

Import modules for Spark Session and regex 

Note: regexes can be used to search strings for patterns. Here is a [reference](https://realpython.com/regex-python/?utm_source=chatgpt.com).

In [4]:
from pyspark.sql import SparkSession
import re

spark = SparkSession.builder.getOrCreate()
sc = spark.sparkContext

KeyboardInterrupt:

In [ ]:
import socket
print(socket.gethostname())
print(socket.gethostbyname(socket.gethostname()))

DESKTOP-9HVGF1I
10.5.0.2

:

11) (1 PT) Read in the logfile.txt data

12) (1 PT) Count the number of rows of data

13) (2 PTS) Show the first five lines containing WARN.  
    Write code to count and print the total number of lines containing WARN.

14) (2 PTS) Write a word count program to count the number of each of these log levels:  

- WARN
- INFO
- DEBUG
- ERROR

15. (2 PTS) Return the three log lines with the highest latency. This is reported in the log as `latency_ms`.

Note: There may be more than three lines tied for highest latency, in which case, just show three records.

16. (2 PTS) Compute the average latency for each service. Ignore log entries without a latency_ms.